name: Pipeline Frontend

on:
  push:
    branches: ["main"]

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build & Publish Frontend Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.IMAGE_TAG }}
      image_repo: ${{ steps.set-tag.outputs.IMAGE_REPO }}
    steps:
      - uses: actions/checkout@v4

      - name: Set image repo, tag, and build mode
        id: set-tag
        run: |
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-8)

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "IMAGE_REPO=it-forelead/teamflow-prod" >> $GITHUB_OUTPUT
            echo "BUILD_MODE=production" >> $GITHUB_ENV
          fi

          echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.set-tag.outputs.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          build-args: |
            BUILD_MODE=${{ env.BUILD_MODE }}